-- Create the database separately, then execute this file while connected to mwm.

CREATE TABLE IF NOT EXISTS clientes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  cpf_cnpj VARCHAR(20) NOT NULL UNIQUE,
  email VARCHAR(254),
  telefone VARCHAR(30),
  endereco VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS funcionarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  cargo VARCHAR(100) NOT NULL,
  matricula VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS usuarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  email VARCHAR(254) NOT NULL UNIQUE,
  senha_hash VARCHAR(255) NOT NULL,
  perfil VARCHAR(20) NOT NULL DEFAULT 'funcionario' CHECK (perfil IN ('admin', 'funcionario')),
  funcionario_id INTEGER REFERENCES funcionarios(id) ON DELETE SET NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS veiculos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id INTEGER NOT NULL,
  placa VARCHAR(10) NOT NULL UNIQUE,
  marca VARCHAR(80) NOT NULL,
  modelo VARCHAR(80) NOT NULL,
  cor VARCHAR(40),
  quilometragem INTEGER NOT NULL DEFAULT 0 CHECK (quilometragem >= 0),
  ultima_visita DATE,
  carroceria VARCHAR(40),
  CONSTRAINT fk_veiculos_cliente
    FOREIGN KEY (cliente_id) REFERENCES clientes(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_veiculos_cliente ON veiculos(cliente_id);

CREATE TABLE IF NOT EXISTS ordens_servico (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo VARCHAR(200) NOT NULL,
  cliente_id INTEGER,
  veiculo_id INTEGER,
  responsavel_id INTEGER,
  status VARCHAR(20) NOT NULL DEFAULT 'pendente'
    CHECK (status IN ('em_andamento', 'finalizado', 'pendente')),
  observacao TEXT,
  data_inicio TIMESTAMP,
  data_fim TIMESTAMP,
  tempo_decorrido_minutos INTEGER NOT NULL DEFAULT 0 CHECK (tempo_decorrido_minutos >= 0),
  valor NUMERIC(10, 2) NOT NULL DEFAULT 0.00 CHECK (valor >= 0),
  CONSTRAINT fk_ordens_cliente
    FOREIGN KEY (cliente_id) REFERENCES clientes(id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_ordens_veiculo
    FOREIGN KEY (veiculo_id) REFERENCES veiculos(id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_ordens_responsavel
    FOREIGN KEY (responsavel_id) REFERENCES funcionarios(id)
    ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_ordens_status ON ordens_servico(status);
CREATE INDEX IF NOT EXISTS idx_ordens_data_inicio ON ordens_servico(data_inicio);
CREATE INDEX IF NOT EXISTS idx_ordens_cliente ON ordens_servico(cliente_id);
CREATE INDEX IF NOT EXISTS idx_ordens_veiculo ON ordens_servico(veiculo_id);
CREATE INDEX IF NOT EXISTS idx_ordens_responsavel ON ordens_servico(responsavel_id);

INSERT INTO clientes (id, nome, cpf_cnpj, email, telefone, endereco)
VALUES
  (1, 'João da Silva', '000.000.000-00', 'joao@email.com', '(49) 99999-9999', 'Rua Exemplo, 100'),
  (2, 'Robson', '54875480210', 'robson.com', '(49) 99999-9999', 'Rua Exemplo, 100')
ON CONFLICT (id) DO UPDATE SET
  nome = EXCLUDED.nome, email = EXCLUDED.email, telefone = EXCLUDED.telefone, endereco = EXCLUDED.endereco;

INSERT INTO funcionarios (id, nome, cargo, matricula)
VALUES (1, 'Carlos Oliveira', 'Mecânico', 'FUNC001')
ON CONFLICT (id) DO UPDATE SET
  nome = EXCLUDED.nome, cargo = EXCLUDED.cargo;

INSERT INTO usuarios (id, nome, email, senha_hash, perfil, funcionario_id)
VALUES (1, 'Alex Pires', 'admin@oficina.com', '$2a$12$Vw/kTqu9gLEILUNbXlnwh.SSqe2xaA6Roj4nrpj/aq/ZLL0uw38cS', 'admin', NULL)
ON CONFLICT (id) DO UPDATE SET
  nome = EXCLUDED.nome, email = EXCLUDED.email, senha_hash = EXCLUDED.senha_hash,
  perfil = EXCLUDED.perfil, ativo = TRUE;

INSERT INTO veiculos (id, cliente_id, placa, marca, modelo, cor, quilometragem, ultima_visita, carroceria)
VALUES (1, 1, 'ABC1D23', 'Volkswagen', 'Gol', 'Prata', 85000, '2026-08-20', 'Hatch')
ON CONFLICT (id) DO UPDATE SET
  cliente_id = EXCLUDED.cliente_id, marca = EXCLUDED.marca, modelo = EXCLUDED.modelo,
  cor = EXCLUDED.cor, quilometragem = EXCLUDED.quilometragem, ultima_visita = EXCLUDED.ultima_visita,
  carroceria = EXCLUDED.carroceria;

INSERT INTO ordens_servico
  (id, titulo, cliente_id, veiculo_id, responsavel_id, status, observacao, data_inicio, data_fim, tempo_decorrido_minutos, valor)
VALUES
  (1, 'Revisão geral', 1, 1, 1, 'em_andamento', 'Realizar revisão dos componentes.', '2026-09-04 08:30:00', NULL, 0, 120.00)
ON CONFLICT (id) DO UPDATE SET
  titulo = EXCLUDED.titulo, cliente_id = EXCLUDED.cliente_id, veiculo_id = EXCLUDED.veiculo_id,
  responsavel_id = EXCLUDED.responsavel_id, status = EXCLUDED.status, observacao = EXCLUDED.observacao,
  data_inicio = EXCLUDED.data_inicio, data_fim = EXCLUDED.data_fim,
  tempo_decorrido_minutos = EXCLUDED.tempo_decorrido_minutos, valor = EXCLUDED.valor;

SELECT setval(pg_get_serial_sequence('clientes', 'id'), COALESCE((SELECT MAX(id) FROM clientes), 1));
SELECT setval(pg_get_serial_sequence('funcionarios', 'id'), COALESCE((SELECT MAX(id) FROM funcionarios), 1));
SELECT setval(pg_get_serial_sequence('usuarios', 'id'), COALESCE((SELECT MAX(id) FROM usuarios), 1));
SELECT setval(pg_get_serial_sequence('veiculos', 'id'), COALESCE((SELECT MAX(id) FROM veiculos), 1));
SELECT setval(pg_get_serial_sequence('ordens_servico', 'id'), COALESCE((SELECT MAX(id) FROM ordens_servico), 1));